# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
 branches:
  include:
    - main
    - develop
    - acceptance
 paths:
  include:
     - src/** 
   
    
 
pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: npm install    
  displayName: 'npm install'

- script: gulp bundle --ship
  displayName: 'gulp bundle'

- script: gulp package-solution --ship
  displayName: 'gulp package-solution'

- task: CopyFiles@2
  inputs:
    contents: '**/*.sppkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/spfx-targeted-script-editor'

- task: PublishBuildArtifacts@1
  inputs:
   PathtoPublish: '$(Build.ArtifactStagingDirectory)/spfx-targeted-script-editor'
   ArtifactName: 'spfx-targeted-script-editor'
    